### ISSUE TITLE
Question about vector notation in course materials

### ISSUE THREAD

**Issue by lazarjov** [moorepants/learn-multibody-dynamics#142] opened 2023-03-02 21:23 UTC
Hey there,

I have a very minor question: why is the vector notation in course materials with the bar, instead of the arrow?

Thanks,
Lazar

**Comment by moorepants** [comment] 2023-03-03 06:07
Because that is what I use to indicate a vector.

**Comment by moorepants** [comment] 2023-03-03 06:10
This is a duplicate of https://github.com/moorepants/learn-multibody-dynamics/issues/92, so I'll close it. More info is there.

**Closed by moorepants** 2023-03-03 06:10 UTC
